version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - database
      - redis
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/laundry
  database:
    build: ./backend
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - laundry:/data/db
  redis:
    build: ./backend
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./backend/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  laundry:
