version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - 8080:8000
    env_file:
      - ./backend/.env
    depends_on:
      - database
      - redis
  database:
    image: mongo:6-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - laundry:/data/db
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data
volumes:
  laundry:
  cache:
